# site name
prefixName: Renaissance.の
siteName: Ranshi
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url:
description: 成为更好的自己，才能守护最好的你
cdn: https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.4
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎来到我的博客，请尽情浏览吧<(￣︶￣)↗[GO!]
lazyloadImg: https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.0/img/loader/loading.jpg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档:
    {
      path: /archives,
      fa: fa-archive faa-shake,
      submenus:
        {
          技术: { path: /categories/技术/, fa: fa-code },
          生活: { path: /categories/生活/, fa: fa-file-text-o },
          资源: { path: /categories/资源/, fa: fa-cloud-download },
          随想: { path: /categories/随想/, fa: fa-commenting-o },
          转载: { path: /categories/转载/, fa: fa-book },
        },
    }
  清单:
    {
      path: javascript:;,
      fa: fa-list-ul faa-vertical,
      submenus:
        {
          书单: { path: /tags/悦读/, fa: fa-th-list faa-bounce },
          番组: { path: /bangumi/, fa: fa-film faa-vertical },
          歌单: { path: /music/, fa: fa-headphones },
          图集: { path: /tags/图集/, fa: fa-photo },
        },
    }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于:
    {
      path: /,
      fa: fa-leaf faa-wrench,
      submenus:
        {
          我？: { path: /about/, fa: fa-meetup },
          主题: { path: /theme-sakura/, fa: iconfont icon-sakura },
          Lab: { path: /lab/, fa: fa-cogs },
        },
    }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 12
# 背景图片 更好的修改
bg:
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.45/2021.5.20/80438411_p0.png
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.45/2021.5.20/89181465_p0.png
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.45/2021.5.20/87706186_p0.jpg
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.45/2021.5.20/89193760_p0.jpg
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.45/2021.5.20/81943456_p0.jpg
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.45/2021.5.20/60006073_p0.jpg
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.0/img/cover/bg8.jpg.webp
    - https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.0/img/cover/bg9.jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {
      url: /theme-sakura/,
      title: Sakura,
      desc: 本站 hexo 主题,
      img: /img/startdash/sakura.md.png,
    }
  - {
      url: https://space.bilibili.com/12804030,
      title: Bilibili,
      desc: 博主的b站视频,
      img: /img/startdash/bilibili.jpg,
    }

# your site build time or founded date
siteBuildingTime: 03/11/2020

#social  url, img PC端配置
social:
  github: { url: https://github.com/Zranshi, img: /img/social/github.png }
  wangyiyun:
    {
      url: https://music.163.com/#/user/home?id=319231686,
      img: /img/social/wangyiyun.png,
    }
  zhihu:
    { url: https://www.zhihu.com/people/ran-shi-2, img: /img/social/zhihu.png }

#social  url, img 移动端配置
msocial:
  github: { url: https://github.com/Zranshi, fa: fa-github, color: 333 }

donate:
  alipay: https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.4/img/custom/donate/a.png
  wechat: https://cdn.jsdelivr.net/gh/Zranshi/CDN@1.4/img/custom/donate/w.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: mad.flv

aplayer:
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: pyh3waP7SKCHyFgcyByVN16c-gzGzoHsz
v_appKey: GieWKHddp2zS74VdyalPK69u

rss: /atom.xml
